name: 🪙 Crypto Market Alert
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install jq zsh curl -y
      - env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_URL: "https://data.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT"
        run: |
          mkdir -p logs
          ./bin/fetch_data.sh && source ./bin/parsers/crypto.sh && ./bin/notify_discord.sh
